dependencies:
  # - <organization/repo>@<version>
  - aave/protocol-v2@1.0.1
compiler:
  solc: 
    remappings:
    - '@aave=aave/protocol-v2@1.0.1'
networks:
  kovan:
    # searching for "kovan WETH contract etherscan" as he does in the video takes me to a page where the contract appears
    # to be down, so this weth_token value is for rinkeby. However, rinkeby does not appear to support the lending pool addresses provider
    # RINKEBY weth_token: '0xc778417e063141139fce010982780140aa0cd5ab'
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c' #KOVAN copied from screen on YT vid
    lending_pool_addresses_provider: '0x88757f2f99175387aB4C6a4b3067c77A695b0349'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
    dai_token: '0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD'
  mainnet-fork:
    weth_token: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
    lending_pool_addresses_provider: '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'
    dai_eth_price_feed: '0x773616E4d11A78F511299002da57A0a94577F1f4'
    dai_token: '0x6b175474e89094c44da98b954eedeac495271d0f'
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env